### ISSUE TITLE
Navigation Explanation

### ISSUE THREAD

**Issue by JBlaz** [xvermilion/ModularizationSample#1]
Sorry if I am putting this in the wrong place but I am curious what benefit the `Navigation` portion of the repo is? Seems like more work to manage a string that is a copy of the activity location than to just initialize the activity? Any response is helpful. I haven't found a great way to navigate and am hoping this is it.

**Comment by Marchosiax** [comment]
Suppose we don't use the Navigation module and suppose there is an activity which we want to navigate to it from 3 different modules. We have to duplicate the navigation process (meaning getting the intent of the activity using it's location's String) in each modules. It wouldn't be the best practice. Overall though, I agree it's not the best way. I'm currently working to make it a bit more interesting.

**Comment by JBlaz** [comment]
I see. That makes sense, I guess I was thinking in the small not the large. Several modules all needing to be aware of a single Activity. Thank you for responding.
